In [ ]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# 加载数据
digits = load_digits()
data = digits.data
x_train, x_test, y_train, y_test = train_test_split(data, digits.target, test_size=0.2)

# 数据归一化
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# 构建模型
model = Sequential([
    Dense(units=200, activation='relu', input_shape=(64,)),  # 输入特征数为64
    Dense(units=100, activation='relu'),
    Dense(units=75, activation='relu'),
    Dense(units=50, activation='relu'),
    Dense(units=10, activation='softmax')  # 输出10个类别
])

# 编译模型
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 训练模型
model.fit(x_train, y_train, epochs=200, batch_size=32, verbose=1)

# 预测
predictions = model.predict(x_test)


[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [6]:
# import numpy as np
# # 获取分类结果
# predicted_classes = np.argmax(predictions, axis=1)


# cnt = 0
# for i in range(len(y_test)):
#     if predicted_classes[i]==y_test[i]:
#         cnt=cnt+1
                  
# print(cnt/len(y_test))